language: node_js
node_js:
  - lts/*
after_success: npm run-script build
deploy:
  - provider: s3
    access_key_id: $S3_ACCESS_KEY_ID
    secret_access_key: $S3_SECRET_ACCESS_KEY
    bucket: hackathon-bowling
    region: eu-west-2
    acl: public_read
    local_dir: build
    on:
      branch: master
    edge: true
  - provider: pages
    github_token: $GITHUB_TOKEN
    local_dir: build
    on:
      branch: master
    edge: true
  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_ACCESS_KEY
    bucket: hackathon-bowling
    local_dir: build
    on:
      branch: master
    edge: true
