language: node_js
node_js:
  - lts/*
before_deploy: npm run-script build
deploy:
  - provider: s3
    access_key_id: "AKIAZO255AVAI42NM4SI"
    secret_access_key:
      secure: "aehxufK5uwHN8AmBvd0Tv7Mup+qu3ErT4SAgqLNXr6e5yvueNAxLV9qClZdYPbOg/tPioZyO2LJKLlBjTSlookjEOhqWFEDzwOEk7VtesuV5lkYDLuRMZjGSKs01eTULX3ZF6RmHl9KvAf+FqOOdQXggZncR7gLSG1TY/DQ2fIdmPf11rtfev3YLtSLDItw0fFn2UyVozSpCuEpZUL56qBxbkFKxFjmTKt4LJ1Or6ZXZ2e7hTRsXrcj8n2XXsiym2bU0UWwMNIbLT2euhnR1EeHv1Lc9H/0SYMyE1+rT4hPCAuS7DwUDHWDj84CCIFxV6dpvL1ygAwB3y4RiUb3eAfFbG1iczT55gSgaJ5LGlQQWzstpeVvJJrZYERfSRllOIRmA+gorgU0oYgFKenTaIVTNJ94euH7nGFGdJG1yp8oSP7aMgcmsG1JFZTnGFgEl+BP9CWqgH1gwzz/VhsUuno6y2rJyRJXpUGhn8BhRfWUEpvwqkq/9eE4Xdh07JofAGxCkinWns9Kr/7qKUt8VF6mD+KoBpwoSg7a/iJXAuxSXHKt4JJjvP7BAAL6/11cIaTb7DYQeYbCnqpGw2LTomQCDzHTn7O5hI+TeZoWu+Gk3wbcA2AphqQi6ZgYM6Dwm6m7+cUWURyDrTXsWHUqea9p5Y3XBkeK5vaY93IVYD0g="
    bucket: "hackathon-bowling"
    region: "eu-west-2"
    acl: public_read
    skip_cleanup: true
    local_dir: build
    on:
      branch: master
  - provider: pages
    github_token:
      secure: "W75GOyUhRufqZVHVyPWTxhczY43/lSnUDVwHjOR9D2DCiAnLZotgmJjzVnNY7BBtYMt4wVBIbjVeLKydOa73mr+MspLSAOEKGdcGy4V4FqVC8+XM1KyFzr+96F8GRH8wDwgy+DPH3vQb+bBPEbuhgwoIGHnV7+9b2gGSMJmdLNc9fW0Zmk9mHsRvrVJ3v7b1tX0YlSQt2WOGI95RfbwGVSLF3nQ+GrRi58rZ7pg0maJLqmX92oVIJ4NfjcjHV3LquprdjoJJuK+I9N6hpN0W/eirQZrh8duI76HmiDwL5R6sUoRc/kzLCu9VURuitVqg5RLru+X658sTyXYzKPgwW5Y/wY7M+rF1LZS4OXrv4Y2WR7od2+6y0qamBIvvf08881Hqqf+MUaQK/Y7xVbDgkk7edE8QYJqhe5cZbJGm6imS9hvfNmMstNQJVhN5Dn9WQX+QhA+EzgKtnKznGknvSJbOWlZxz2oEiHbcivmk+EIYqpkKkUg9FD1n2WBRzlovXusUX68O0yEpfX7dfSQwBqfi3Q8f0aIl0TmdrYrUXeDm0LfG8wDtCIkymnlAqgxFpW/1Jo1U9wogGEy6MCBSuXun2D/CY1U4pmM3AccszDkU7432cvnkht5lByYiIWMK6iFqOURN/YqtFm6SJUwsBE6ZLMLEgM6Hw+JYftSufXU="
    skip_cleanup: true
    local_dir: build
    on:
      branch: master