language: node_js
node_js:
  - lts/*
deploy:
  provider: s3
  access_key_id: "AKIAZO255AVAI42NM4SI"
  secret_access_key:
    secure: "aehxufK5uwHN8AmBvd0Tv7Mup+qu3ErT4SAgqLNXr6e5yvueNAxLV9qClZdYPbOg/tPioZyO2LJKLlBjTSlookjEOhqWFEDzwOEk7VtesuV5lkYDLuRMZjGSKs01eTULX3ZF6RmHl9KvAf+FqOOdQXggZncR7gLSG1TY/DQ2fIdmPf11rtfev3YLtSLDItw0fFn2UyVozSpCuEpZUL56qBxbkFKxFjmTKt4LJ1Or6ZXZ2e7hTRsXrcj8n2XXsiym2bU0UWwMNIbLT2euhnR1EeHv1Lc9H/0SYMyE1+rT4hPCAuS7DwUDHWDj84CCIFxV6dpvL1ygAwB3y4RiUb3eAfFbG1iczT55gSgaJ5LGlQQWzstpeVvJJrZYERfSRllOIRmA+gorgU0oYgFKenTaIVTNJ94euH7nGFGdJG1yp8oSP7aMgcmsG1JFZTnGFgEl+BP9CWqgH1gwzz/VhsUuno6y2rJyRJXpUGhn8BhRfWUEpvwqkq/9eE4Xdh07JofAGxCkinWns9Kr/7qKUt8VF6mD+KoBpwoSg7a/iJXAuxSXHKt4JJjvP7BAAL6/11cIaTb7DYQeYbCnqpGw2LTomQCDzHTn7O5hI+TeZoWu+Gk3wbcA2AphqQi6ZgYM6Dwm6m7+cUWURyDrTXsWHUqea9p5Y3XBkeK5vaY93IVYD0g="
  bucket: "hackathon-bowling"
  acl: public_read
  skip_cleanup: true
  local_dir: build
  on:
    branch: master
