language: node_js
node_js:
  - lts/*
before_deploy: npm run-script build
deploy:
  - provider: s3
    access_key_id: $S3_ACCESS_KEY_ID
    secret_access_key: $S3_SECRET_ACCESS_KEY
    bucket: hackathon-bowling
    region: eu-west-2
    acl: public_read
    skip_cleanup: true
    local_dir: build
    on:
      branch: master
  - provider: pages
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    local_dir: build
    on:
      branch: master
